# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a005f8e23cbaebd79aa2e280a9ac74c14120086beb434e7d1c55430ceddfd63ac4d2ffdd6e2530f392ca62c6eefd76cf7473c4fa60631dff5f9a8561d2638431

test:
  secret_key_base: 4d1d21e86cb33bc0b34991bd2aea286be656dca86ae84fb1b9eb1d866bde6c9279058fb9cbd193a76d3cece349a996ea1ebe5b791e222f1677b2a6ebdd33021a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
